version: "3.8"

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - "3030:443"
      - "8080:80"
    restart: always
    networks:
      oracle_network:
        ipv4_address: 172.16.238.11

  web:
    build:
      context: .
    ports:
      - "3000"
    restart: always
    networks:
      oracle_network:
        ipv4_address: 172.16.238.12

  bundler:
    build: ./bundler
    ports:
      - "3000:3000"
    restart: always 
    environment:
      ENTRYPOINTS: "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
      BUNDLER_SECRET: "0xd7f305cda31c0cb26f900afd16b3fcd697c3c1d00855767a8352d41987643e36"
      BUNDLER_SMART_WALLET: "0x90f007bfaf925a39e63568d8fc4712c81676ff05"
      CHAIN_ID: "11155111"
      ETHEREUM_NODE_URL: "http://3.68.113.82:8545"
      ORACLE_ADDRESS: "0x36bDD3f53826e4359E22edb9C6DD2E81Dd4dEf41"
      DATA_PROVIDER_URL: "172.16.238.14:5000"
    networks:
      oracle_network:
        ipv4_address: 172.16.238.13

  provider:
    build: ./bundler/data-provider-example
    ports:
      - "5000"
    restart: always
    networks:
      oracle_network:
        ipv4_address: 172.16.238.14

networks:
  oracle_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
