[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc = "0.8.29"
optimizer = true
optimizer_runs = 200

# Required for OpenZeppelin Foundry Upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# Allow reading the deployments directory
fs_permissions = [{ access = "read-write", path = "./deployments" }]

# try to have more deterministic output
# auto_detect_remappings = false
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false

[profile.default.optimizer_details]
# constantOptimizer = true
yul = true